version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.23.0
    - 7.24.0
  - dependency-name: discord.js
    versions:
    - 12.5.2
  - dependency-name: eslint-config-aqua
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: systeminformation
    versions:
    - 4.34.11
    - 4.34.12
    - 4.34.13
    - 4.34.14
    - 4.34.15
    - 4.34.9
  - dependency-name: fs-extra
    versions:
    - 9.1.0
  - dependency-name: bootstrap
    versions:
    - 4.6.0
